
[21:28:09 INFO]: zLqvely has made the advancement [Remote Getaway]
[21:28:09 INFO]: Chiyogami : INFO > Try wait world_the_end -> world_the_end
[21:28:09 INFO]: Chiyogami : INFO > Wait for world_the_end -> world_the_end
[21:28:19 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:28:19 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:28:19 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:28:19 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:28:19 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:28:19 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:28:19 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:28:19 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: Current Thread: Server thread
[21:28:19 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:28:19 ERROR]:       Stack:
[21:28:19 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:28:19 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:28:19 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:28:19 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:28:19 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:28:19 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:28:19 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:28:19 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:28:19 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:19 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: World thread dump : world
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: Current Thread: WorldTickThread[2]
[21:28:19 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:28:19 ERROR]:       Stack:
[21:28:19 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:19 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:19 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: World thread dump : world_nether
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: Current Thread: WorldTickThread[0]
[21:28:19 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:28:19 ERROR]:       Stack:
[21:28:19 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:19 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:19 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: World thread dump : world_the_end
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: Current Thread: WorldTickThread[1]
[21:28:19 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:28:19 ERROR]:       Stack:
[21:28:19 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:28:19 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:28:19 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:28:19 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:28:19 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:28:19 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:28:19 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:28:19 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:28:19 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:28:19 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:28:19 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:28:19 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:28:19 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:28:19 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:28:19 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:28:19 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:19 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:19 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:19 ERROR]: ------------------------------
[21:28:19 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:28:19 ERROR]: ------------------------------
[21:28:24 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:28:24 ERROR]: The server has not responded for 15 seconds! Creating thread dump
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:28:24 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:28:24 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:28:24 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:28:24 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:28:24 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:28:24 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: Current Thread: Server thread
[21:28:24 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:28:24 ERROR]:       Stack:
[21:28:24 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:28:24 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:28:24 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:28:24 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:28:24 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:28:24 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:28:24 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:28:24 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:28:24 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:24 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: World thread dump : world
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: Current Thread: WorldTickThread[2]
[21:28:24 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:28:24 ERROR]:       Stack:
[21:28:24 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:24 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:24 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: World thread dump : world_nether
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: Current Thread: WorldTickThread[0]
[21:28:24 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:28:24 ERROR]:       Stack:
[21:28:24 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:24 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:24 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: World thread dump : world_the_end
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: Current Thread: WorldTickThread[1]
[21:28:24 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:28:24 ERROR]:       Stack:
[21:28:24 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:28:24 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:28:24 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:28:24 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:28:24 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:28:24 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:28:24 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:28:24 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:28:24 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:28:24 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:28:24 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:28:24 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:28:24 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:28:24 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:28:24 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:28:24 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:24 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:24 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:24 ERROR]: ------------------------------
[21:28:24 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:28:24 ERROR]: ------------------------------
[21:28:29 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:28:29 ERROR]: The server has not responded for 20 seconds! Creating thread dump
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:28:29 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:28:29 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:28:29 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:28:29 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:28:29 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:28:29 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: Current Thread: Server thread
[21:28:29 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:28:29 ERROR]:       Stack:
[21:28:29 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:28:29 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:28:29 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:28:29 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:28:29 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:28:29 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:28:29 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:28:29 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:28:29 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:29 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: World thread dump : world
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: Current Thread: WorldTickThread[2]
[21:28:29 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:28:29 ERROR]:       Stack:
[21:28:29 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:29 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:29 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: World thread dump : world_nether
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: Current Thread: WorldTickThread[0]
[21:28:29 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:28:29 ERROR]:       Stack:
[21:28:29 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:29 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:29 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: World thread dump : world_the_end
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: Current Thread: WorldTickThread[1]
[21:28:29 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:28:29 ERROR]:       Stack:
[21:28:29 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:28:29 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:28:29 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:28:29 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:28:29 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:28:29 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:28:29 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:28:29 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:28:29 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:28:29 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:28:29 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:28:29 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:28:29 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:28:29 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:28:29 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:28:29 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:29 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:29 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:29 ERROR]: ------------------------------
[21:28:29 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:28:29 ERROR]: ------------------------------
[21:28:34 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:28:34 ERROR]: The server has not responded for 25 seconds! Creating thread dump
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:28:34 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:28:34 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:28:34 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:28:34 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:28:34 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:28:34 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: Current Thread: Server thread
[21:28:34 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:28:34 ERROR]:       Stack:
[21:28:34 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:28:34 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:28:34 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:28:34 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:28:34 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:28:34 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:28:34 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:28:34 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:28:34 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:34 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: World thread dump : world
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: Current Thread: WorldTickThread[2]
[21:28:34 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:28:34 ERROR]:       Stack:
[21:28:34 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:34 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:34 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: World thread dump : world_nether
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: Current Thread: WorldTickThread[0]
[21:28:34 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:28:34 ERROR]:       Stack:
[21:28:34 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:34 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:34 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: World thread dump : world_the_end
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: Current Thread: WorldTickThread[1]
[21:28:34 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:28:34 ERROR]:       Stack:
[21:28:34 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:28:34 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:28:34 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:28:34 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:28:34 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:28:34 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:28:34 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:28:34 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:28:34 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:28:34 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:28:34 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:28:34 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:28:34 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:28:34 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:28:34 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:28:34 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:34 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:34 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:34 ERROR]: ------------------------------
[21:28:34 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:28:34 ERROR]: ------------------------------
[21:28:39 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:28:39 ERROR]: The server has not responded for 30 seconds! Creating thread dump
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:28:39 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:28:39 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:28:39 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:28:39 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:28:39 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:28:39 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: Current Thread: Server thread
[21:28:39 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:28:39 ERROR]:       Stack:
[21:28:39 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:28:39 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:28:39 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:28:39 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:28:39 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:28:39 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:28:39 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:28:39 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:28:39 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:39 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: World thread dump : world
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: Current Thread: WorldTickThread[2]
[21:28:39 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:28:39 ERROR]:       Stack:
[21:28:39 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:39 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:39 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: World thread dump : world_nether
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: Current Thread: WorldTickThread[0]
[21:28:39 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:28:39 ERROR]:       Stack:
[21:28:39 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:39 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:39 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: World thread dump : world_the_end
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: Current Thread: WorldTickThread[1]
[21:28:39 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:28:39 ERROR]:       Stack:
[21:28:39 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:28:39 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:28:39 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:28:39 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:28:39 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:28:39 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:28:39 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:28:39 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:28:39 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:28:39 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:28:39 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:28:39 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:28:39 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:28:39 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:28:39 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:28:39 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:39 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:39 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:39 ERROR]: ------------------------------
[21:28:39 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:28:39 ERROR]: ------------------------------
[21:28:44 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:28:44 ERROR]: The server has not responded for 35 seconds! Creating thread dump
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:28:44 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:28:44 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:28:44 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:28:44 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:28:44 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:28:44 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: Current Thread: Server thread
[21:28:44 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:28:44 ERROR]:       Stack:
[21:28:44 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:28:44 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:28:44 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:28:44 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:28:44 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:28:44 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:28:44 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:28:44 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:28:44 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:44 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: World thread dump : world
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: Current Thread: WorldTickThread[2]
[21:28:44 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:28:44 ERROR]:       Stack:
[21:28:44 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:44 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:44 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: World thread dump : world_nether
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: Current Thread: WorldTickThread[0]
[21:28:44 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:28:44 ERROR]:       Stack:
[21:28:44 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:44 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:44 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: World thread dump : world_the_end
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: Current Thread: WorldTickThread[1]
[21:28:44 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:28:44 ERROR]:       Stack:
[21:28:44 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:28:44 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:28:44 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:28:44 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:28:44 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:28:44 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:28:44 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:28:44 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:28:44 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:28:44 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:28:44 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:28:44 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:28:44 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:28:44 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:28:44 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:28:44 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:44 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:44 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:44 ERROR]: ------------------------------
[21:28:44 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:28:44 ERROR]: ------------------------------
[21:28:49 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:28:49 ERROR]: The server has not responded for 40 seconds! Creating thread dump
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:28:49 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:28:49 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:28:49 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:28:49 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:28:49 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:28:49 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: Current Thread: Server thread
[21:28:49 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:28:49 ERROR]:       Stack:
[21:28:49 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:28:49 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:28:49 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:28:49 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:28:49 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:28:49 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:28:49 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:28:49 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:28:49 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:49 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: World thread dump : world
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: Current Thread: WorldTickThread[2]
[21:28:49 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:28:49 ERROR]:       Stack:
[21:28:49 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:49 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:49 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: World thread dump : world_nether
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: Current Thread: WorldTickThread[0]
[21:28:49 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:28:49 ERROR]:       Stack:
[21:28:49 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:49 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:49 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: World thread dump : world_the_end
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: Current Thread: WorldTickThread[1]
[21:28:49 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:28:49 ERROR]:       Stack:
[21:28:49 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:28:49 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:28:49 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:28:49 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:28:49 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:28:49 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:28:49 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:28:49 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:28:49 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:28:49 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:28:49 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:28:49 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:28:49 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:28:49 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:28:49 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:28:49 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:49 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:49 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:49 ERROR]: ------------------------------
[21:28:49 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:28:49 ERROR]: ------------------------------
[21:28:54 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:28:54 ERROR]: The server has not responded for 45 seconds! Creating thread dump
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:28:54 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:28:54 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:28:54 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:28:54 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:28:54 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:28:54 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: Current Thread: Server thread
[21:28:54 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:28:54 ERROR]:       Stack:
[21:28:54 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:28:54 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:28:54 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:28:54 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:28:54 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:28:54 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:28:54 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:28:54 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:28:54 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:54 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: World thread dump : world
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: Current Thread: WorldTickThread[2]
[21:28:54 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:28:54 ERROR]:       Stack:
[21:28:54 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:54 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:54 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: World thread dump : world_nether
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: Current Thread: WorldTickThread[0]
[21:28:54 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:28:54 ERROR]:       Stack:
[21:28:54 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:54 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:54 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: World thread dump : world_the_end
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: Current Thread: WorldTickThread[1]
[21:28:54 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:28:54 ERROR]:       Stack:
[21:28:54 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:28:54 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:28:54 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:28:54 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:28:54 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:28:54 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:28:54 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:28:54 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:28:54 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:28:54 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:28:54 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:28:54 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:28:54 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:28:54 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:28:54 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:28:54 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:54 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:54 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:54 ERROR]: ------------------------------
[21:28:54 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:28:54 ERROR]: ------------------------------
[21:28:59 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:28:59 ERROR]: The server has not responded for 50 seconds! Creating thread dump
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:28:59 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:28:59 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:28:59 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:28:59 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:28:59 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:28:59 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: Current Thread: Server thread
[21:28:59 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:28:59 ERROR]:       Stack:
[21:28:59 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:28:59 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:28:59 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:28:59 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:28:59 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:28:59 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:28:59 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:28:59 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:28:59 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:59 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: World thread dump : world
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: Current Thread: WorldTickThread[2]
[21:28:59 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:28:59 ERROR]:       Stack:
[21:28:59 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:59 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:59 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: World thread dump : world_nether
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: Current Thread: WorldTickThread[0]
[21:28:59 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:28:59 ERROR]:       Stack:
[21:28:59 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:59 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:59 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: World thread dump : world_the_end
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: Current Thread: WorldTickThread[1]
[21:28:59 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:28:59 ERROR]:       Stack:
[21:28:59 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:28:59 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:28:59 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:28:59 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:28:59 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:28:59 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:28:59 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:28:59 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:28:59 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:28:59 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:28:59 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:28:59 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:28:59 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:28:59 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:28:59 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:28:59 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:28:59 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:28:59 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:28:59 ERROR]: ------------------------------
[21:28:59 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:28:59 ERROR]: ------------------------------
[21:29:04 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:29:04 ERROR]: The server has not responded for 55 seconds! Creating thread dump
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:29:04 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:29:04 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:29:04 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:29:04 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:29:04 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:29:04 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: Current Thread: Server thread
[21:29:04 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:29:04 ERROR]:       Stack:
[21:29:04 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:29:04 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:29:04 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:29:04 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:29:04 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:29:04 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:29:04 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:29:04 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:29:04 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:04 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: World thread dump : world
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: Current Thread: WorldTickThread[2]
[21:29:04 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:29:04 ERROR]:       Stack:
[21:29:04 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:04 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:04 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: World thread dump : world_nether
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: Current Thread: WorldTickThread[0]
[21:29:04 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:29:04 ERROR]:       Stack:
[21:29:04 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:04 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:04 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: World thread dump : world_the_end
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: Current Thread: WorldTickThread[1]
[21:29:04 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:29:04 ERROR]:       Stack:
[21:29:04 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:29:04 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:29:04 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:29:04 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:29:04 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:29:04 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:29:04 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:29:04 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:29:04 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:29:04 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:29:04 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:29:04 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:29:04 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:29:04 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:29:04 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:29:04 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:04 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:04 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:04 ERROR]: ------------------------------
[21:29:04 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:29:04 ERROR]: ------------------------------
[21:29:05 WARN]: [spark] Timed out waiting for world statistics
[21:29:09 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-DEV-09e7d11 (MC: 1.21.1) ---
[21:29:09 ERROR]: The server has not responded for 60 seconds! Creating thread dump
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:29:09 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:29:09 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:29:09 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:29:09 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:29:09 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:29:09 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: Current Thread: Server thread
[21:29:09 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:29:09 ERROR]:       Stack:
[21:29:09 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:29:09 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:29:09 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:29:09 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:29:09 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:29:09 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:29:09 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:29:09 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:29:09 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:09 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: World thread dump : world
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: Current Thread: WorldTickThread[2]
[21:29:09 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:29:09 ERROR]:       Stack:
[21:29:09 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:09 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:09 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: World thread dump : world_nether
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: Current Thread: WorldTickThread[0]
[21:29:09 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:29:09 ERROR]:       Stack:
[21:29:09 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:09 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:09 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: World thread dump : world_the_end
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: Current Thread: WorldTickThread[1]
[21:29:09 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:29:09 ERROR]:       Stack:
[21:29:09 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:29:09 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:29:09 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:29:09 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:29:09 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:29:09 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:29:09 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:29:09 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:29:09 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:29:09 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:29:09 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:29:09 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:29:09 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:29:09 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:29:09 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:29:09 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:09 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:09 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:09 ERROR]: ------------------------------
[21:29:09 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[21:29:09 ERROR]: ------------------------------
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: The server has stopped responding! This is (probably) not a Paper bug.
[21:29:10 ERROR]: If you see a plugin in the Server thread dump below, then please report it to that author
[21:29:10 ERROR]:        *Especially* if it looks like HTTP or MySQL operations are occurring
[21:29:10 ERROR]: If you see a world save or edit, then it means you did far more than your server can handle at once
[21:29:10 ERROR]:        If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes
[21:29:10 ERROR]: If you are unsure or still think this is a Paper bug, please report this to https://github.com/PaperMC/Paper/issues
[21:29:10 ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[21:29:10 ERROR]: Paper version: 1.21.1-DEV-09e7d11 (MC: 1.21.1)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[21:29:10 ERROR]: Ticking entity: minecraft:ender_pearl, entity class: net.minecraft.world.entity.projectile.ThrownEnderpearl
[21:29:10 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[21:29:10 ERROR]: Entity UUID: 21707bc6-0a05-41e1-b260-545e12a5df16
[21:29:10 ERROR]: Position: world: 'world_the_end' at location (78.21579372213277, 75.30003056496723, 56.97084440423833)
[21:29:10 ERROR]: Velocity: (1.2039720101791274, -0.33442690530413755, 1.0268971694684104) (in blocks per tick)
[21:29:10 ERROR]: Entity AABB: AABB[78.09079372213277, 75.30003056496723, 56.84584440423833] -> [78.34079372213277, 75.55003056496723, 57.09584440423833]
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Server thread
[21:29:10 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:29:10 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:29:10 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: World thread dump : world
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: WorldTickThread[2]
[21:29:10 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: World thread dump : world_nether
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: WorldTickThread[0]
[21:29:10 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: World thread dump : world_the_end
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: WorldTickThread[1]
[21:29:10 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:29:10 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:29:10 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:29:10 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:29:10 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:29:10 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:29:10 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:29:10 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:29:10 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:29:10 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:29:10 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:29:10 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:29:10 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Entire Thread Dump:
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Reference Handler
[21:29:10 ERROR]:       PID: 9 | Suspended: false | Native: false | State: RUNNABLE
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.Reference.processPendingReferences(Reference.java:246)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Finalizer
[21:29:10 ERROR]:       PID: 10 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Object.wait0(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Object.wait(Object.java:378)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Object.wait(Object.java:352)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:166)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Signal Dispatcher
[21:29:10 ERROR]:       PID: 11 | Suspended: false | Native: false | State: RUNNABLE
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Attach Listener
[21:29:10 ERROR]:       PID: 12 | Suspended: false | Native: false | State: RUNNABLE
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Notification Thread
[21:29:10 ERROR]:       PID: 27 | Suspended: false | Native: false | State: RUNNABLE
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Common-Cleaner
[21:29:10 ERROR]:       PID: 28 | Suspended: false | Native: false | State: TIMED_WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1852)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:79)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:151)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:229)
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: DestroyJavaVM
[21:29:10 ERROR]:       PID: 47 | Suspended: false | Native: false | State: RUNNABLE
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: WindowsStreamPump
[21:29:10 ERROR]:       PID: 51 | Suspended: false | Native: false | State: RUNNABLE
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               org.fusesource.jansi.internal.Kernel32.WaitForSingleObject(Native Method)
[21:29:10 ERROR]:               org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:138)
[21:29:10 ERROR]:               org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460)
[21:29:10 ERROR]:               org.jline.terminal.impl.AbstractWindowsTerminal$$Lambda/0x000002290512e000.run(Unknown Source)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Log4j2-AsyncAppenderEventDispatcher-1-Async
[21:29:10 ERROR]:       PID: 53 | Suspended: false | Native: false | State: RUNNABLE
[21:29:10 ERROR]:       Thread is waiting on monitor(s):
[21:29:10 ERROR]:               Locked on:org.jline.terminal.impl.AbstractWindowsConsoleWriter.write(AbstractWindowsConsoleWriter.java:27)
[21:29:10 ERROR]:               Locked on:java.base@23.0.1/java.io.Writer.write(Writer.java:219)
[21:29:10 ERROR]:               Locked on:java.base@23.0.1/java.io.PrintWriter.write(PrintWriter.java:528)
[21:29:10 ERROR]:               Locked on:net.minecrell.terminalconsole.TerminalConsoleAppender.print(TerminalConsoleAppender.java:263)
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               org.fusesource.jansi.internal.Kernel32.WriteConsoleW(Native Method)
[21:29:10 ERROR]:               org.jline.terminal.impl.jansi.win.JansiWinConsoleWriter.writeConsole(JansiWinConsoleWriter.java:27)
[21:29:10 ERROR]:               org.jline.terminal.impl.AbstractWindowsConsoleWriter.write(AbstractWindowsConsoleWriter.java:27)
[21:29:10 ERROR]:               java.base@23.0.1/java.io.Writer.implWrite(Writer.java:229)
[21:29:10 ERROR]:               java.base@23.0.1/java.io.Writer.write(Writer.java:219)
[21:29:10 ERROR]:               java.base@23.0.1/java.io.PrintWriter.implWrite(PrintWriter.java:536)
[21:29:10 ERROR]:               java.base@23.0.1/java.io.PrintWriter.write(PrintWriter.java:528)
[21:29:10 ERROR]:               java.base@23.0.1/java.io.PrintWriter.append(PrintWriter.java:1374)
[21:29:10 ERROR]:               java.base@23.0.1/java.io.PrintWriter.append(PrintWriter.java:64)
[21:29:10 ERROR]:               org.jline.utils.Curses.doTputs(Curses.java:460)
[21:29:10 ERROR]:               org.jline.utils.Curses.tputs(Curses.java:60)
[21:29:10 ERROR]:               org.jline.terminal.impl.AbstractTerminal.puts(AbstractTerminal.java:185)
[21:29:10 ERROR]:               org.jline.utils.Display.update(Display.java:290)
[21:29:10 ERROR]:               org.jline.utils.Display.update(Display.java:103)
[21:29:10 ERROR]:               org.jline.reader.impl.LineReaderImpl.printAbove(LineReaderImpl.java:770)
[21:29:10 ERROR]:               net.minecrell.terminalconsole.TerminalConsoleAppender.print(TerminalConsoleAppender.java:263)
[21:29:10 ERROR]:               net.minecrell.terminalconsole.TerminalConsoleAppender.append(TerminalConsoleAppender.java:256)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:89)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:89)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatch(AsyncAppenderEventDispatcher.java:127)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:91)
[21:29:10 ERROR]:               org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:73)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: JNA Cleaner
[21:29:10 ERROR]:       PID: 55 | Suspended: false | Native: false | State: TIMED_WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1852)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:79)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:151)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:229)
[21:29:10 ERROR]:               com.sun.jna.internal.Cleaner$CleanerThread.run(Cleaner.java:154)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Timer hack thread
[21:29:10 ERROR]:       PID: 62 | Suspended: false | Native: false | State: TIMED_WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.sleepNanos0(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.sleepNanos(Thread.java:496)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.sleep(Thread.java:527)
[21:29:10 ERROR]:               net.minecraft.Util$7.run(Util.java:785)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Yggdrasil Key Fetcher
[21:29:10 ERROR]:       PID: 63 | Suspended: false | Native: false | State: TIMED_WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1763)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Worker-Main-1
[21:29:10 ERROR]:       PID: 66 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Worker-Main-2
[21:29:10 ERROR]:       PID: 67 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Worker-Main-3
[21:29:10 ERROR]:       PID: 68 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Worker-Main-4
[21:29:10 ERROR]:       PID: 69 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Worker-Main-5
[21:29:10 ERROR]:       PID: 70 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Worker-Main-6
[21:29:10 ERROR]:       PID: 71 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Worker-Main-7
[21:29:10 ERROR]:       PID: 72 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Worker-Main-8
[21:29:10 ERROR]:       PID: 73 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Server thread
[21:29:10 ERROR]:       PID: 74 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:500)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.get(FutureTask.java:190)
[21:29:10 ERROR]:               world.chiyogami.thread.WorldThreadPool.doTick(WorldThreadPool.java:73)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837)
[21:29:10 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1599)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x0000022905c751b8.run(Unknown Source)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Paper Common Worker #0
[21:29:10 ERROR]:       PID: 82 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Paper Common Worker #1
[21:29:10 ERROR]:       PID: 83 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Paper Common Worker #2
[21:29:10 ERROR]:       PID: 84 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Paper Common Worker #3
[21:29:10 ERROR]:       PID: 85 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Paper Common Worker #4
[21:29:10 ERROR]:       PID: 86 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Paper Common Worker #5
[21:29:10 ERROR]:       PID: 87 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: RegionFile I/O Thread #0
[21:29:10 ERROR]:       PID: 88 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Paper Watchdog Thread
[21:29:10 ERROR]:       PID: 89 | Suspended: false | Native: false | State: RUNNABLE
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.management@23.0.1/sun.management.ThreadImpl.dumpThreads0(Native Method)
[21:29:10 ERROR]:               java.management@23.0.1/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:518)
[21:29:10 ERROR]:               java.management@23.0.1/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:506)
[21:29:10 ERROR]:               org.spigotmc.WatchdogThread.run(WatchdogThread.java:209)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Server console handler
[21:29:10 ERROR]:       PID: 76 | Suspended: false | Native: false | State: TIMED_WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1852)
[21:29:10 ERROR]:               org.jline.utils.NonBlockingPumpReader.read(NonBlockingPumpReader.java:78)
[21:29:10 ERROR]:               org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57)
[21:29:10 ERROR]:               org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160)
[21:29:10 ERROR]:               org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
[21:29:10 ERROR]:               org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
[21:29:10 ERROR]:               org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923)
[21:29:10 ERROR]:               org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956)
[21:29:10 ERROR]:               org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651)
[21:29:10 ERROR]:               org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468)
[21:29:10 ERROR]:               net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158)
[21:29:10 ERROR]:               net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[21:29:10 ERROR]:               net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:117)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: pool-8-thread-1
[21:29:10 ERROR]:       PID: 90 | Suspended: false | Native: false | State: TIMED_WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1763)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Netty Server IO #0
[21:29:10 ERROR]:       PID: 91 | Suspended: false | Native: true | State: RUNNABLE
[21:29:10 ERROR]:       Thread is waiting on monitor(s):
[21:29:10 ERROR]:               Locked on:java.base@23.0.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
[21:29:10 ERROR]:               Locked on:java.base@23.0.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/sun.nio.ch.WEPoll.wait(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:114)
[21:29:10 ERROR]:               java.base@23.0.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
[21:29:10 ERROR]:               java.base@23.0.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:147)
[21:29:10 ERROR]:               io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
[21:29:10 ERROR]:               io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:879)
[21:29:10 ERROR]:               io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526)
[21:29:10 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:29:10 ERROR]:               io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: spark-monitoring-thread
[21:29:10 ERROR]:       PID: 92 | Suspended: false | Native: false | State: TIMED_WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1763)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Paper Async Task Handler Thread - 0
[21:29:10 ERROR]:       PID: 93 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Craft Async Scheduler Management Thread
[21:29:10 ERROR]:       PID: 97 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: WorldTickThread[0]
[21:29:10 ERROR]:       PID: 100 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: WorldTickThread[1]
[21:29:10 ERROR]:       PID: 101 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1908)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1942)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2116)
[21:29:10 ERROR]:               world.chiyogami.thread.WorldThread.runWorldTaskThreadSafely(WorldThread.java:216)
[21:29:10 ERROR]:               net.minecraft.world.entity.Entity.changeDimension(Entity.java:3822)
[21:29:10 ERROR]:               net.minecraft.world.entity.Entity.handlePortal(Entity.java:3275)
[21:29:10 ERROR]:               net.minecraft.world.entity.Entity.postTick(Entity.java:857)
[21:29:10 ERROR]:               net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1249)
[21:29:10 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x000002290642baa0.accept(Unknown Source)
[21:29:10 ERROR]:               net.minecraft.world.level.Level.guardEntityTick(Level.java:1421)
[21:29:10 ERROR]:               net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737)
[21:29:10 ERROR]:               net.minecraft.server.level.ServerLevel$$Lambda/0x0000022906304448.accept(Unknown Source)
[21:29:10 ERROR]:               net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[21:29:10 ERROR]:               net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer.lambda$tickChildren$22(MinecraftServer.java:1820)
[21:29:10 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00000229062f3c70.run(Unknown Source)
[21:29:10 ERROR]:               world.chiyogami.thread.WorldThread.run(WorldThread.java:143)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: WorldTickThread[2]
[21:29:10 ERROR]:       PID: 102 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Netty Server IO #1
[21:29:10 ERROR]:       PID: 104 | Suspended: false | Native: true | State: RUNNABLE
[21:29:10 ERROR]:       Thread is waiting on monitor(s):
[21:29:10 ERROR]:               Locked on:java.base@23.0.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
[21:29:10 ERROR]:               Locked on:java.base@23.0.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/sun.nio.ch.WEPoll.wait(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:114)
[21:29:10 ERROR]:               java.base@23.0.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
[21:29:10 ERROR]:               java.base@23.0.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:147)
[21:29:10 ERROR]:               io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
[21:29:10 ERROR]:               io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:879)
[21:29:10 ERROR]:               io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526)
[21:29:10 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:29:10 ERROR]:               io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Paper Async Task Handler Thread - 1
[21:29:10 ERROR]:       PID: 108 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Async Tab Complete Thread - #0
[21:29:10 ERROR]:       PID: 111 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Async Tab Complete Thread - #1
[21:29:10 ERROR]:       PID: 112 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Async Tab Complete Thread - #2
[21:29:10 ERROR]:       PID: 113 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: Async Tab Complete Thread - #3
[21:29:10 ERROR]:       PID: 114 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: DimensionDataIO - .\world - 0
[21:29:10 ERROR]:       PID: 128 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: DimensionDataIO - .\world_nether\DIM-1 - 0
[21:29:10 ERROR]:       PID: 129 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: DimensionDataIO - .\world_the_end\DIM1 - 0
[21:29:10 ERROR]:       PID: 130 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: spark-java-sampler-2-0
[21:29:10 ERROR]:       PID: 135 | Suspended: false | Native: false | State: TIMED_WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1763)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: spark-java-sampler-2-1
[21:29:10 ERROR]:       PID: 136 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1177)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: spark-java-sampler-2-2
[21:29:10 ERROR]:       PID: 137 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1177)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: spark-java-sampler-2-3
[21:29:10 ERROR]:       PID: 138 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1177)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: spark-java-sampler-2-4
[21:29:10 ERROR]:       PID: 139 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1177)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:10 ERROR]: Current Thread: spark-java-sampler-2-5
[21:29:10 ERROR]:       PID: 140 | Suspended: false | Native: false | State: WAITING
[21:29:10 ERROR]:       Stack:
[21:29:10 ERROR]:               java.base@23.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4021)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3967)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1177)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:29:10 ERROR]:               java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
[21:29:10 ERROR]:               java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
[21:29:10 ERROR]: ------------------------------
[21:29:11 INFO]: Stopping server
[21:29:11 INFO]: Saving players
[21:29:11 INFO]: zLqvely lost connection: Server is restarting
[21:29:11 INFO]: zLqvely left the game
[21:29:11 INFO]: Saving worlds
[21:29:11 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[21:29:11 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[21:29:11 INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[21:29:11 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[21:29:11 INFO]: [ChunkHolderManager] Saved 12 block chunks, 8 entity chunks, 0 poi chunks in world 'world' in 0.03s
[21:29:11 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[21:29:11 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[21:29:11 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[21:29:11 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[21:29:11 INFO]: [ChunkHolderManager] Saved 318 block chunks, 4 entity chunks, 0 poi chunks in world 'world_nether' in 0.09s
[21:29:11 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[21:29:11 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[21:29:11 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[21:29:11 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[21:29:12 INFO]: [ChunkHolderManager] Saved 2999 block chunks, 948 entity chunks, 1 poi chunks in world 'world_the_end' in 0.57s
[21:29:12 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[21:29:12 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:29:12 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:29:12 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
